### ISSUE TITLE
select by tagName

### ISSUE THREAD

**Issue by alexflorea2** [ayakashi-io/ayakashi#16]
Hi, I have the following structure that I need to parse, and I can't figure out how to target elements by tagName

```
<div id="containerId">
<span> Random text</span>
<ol>
   <li>li without class</li>
   <li>other li without class</li>
</ol>
</div>
```

My goal is to get all the **li** elements from a container that has an id and then parse the html structure from inside each li.

I have tried code like
```
ayakashi.selectOne("containerId").where({id: {eq: "containerId"}});

    ayakashi
    .select("childLi")
    .where({
        tagName: {
            eq: "li"
        }
    })
    .from("containerId");

    const result = await ayakashi.extract("childLi");
```

other tests where with ```where``` element, tag, etc. 

Thank you in advance!

**Comment by alexflorea2** [comment]
The issue was that i needed to use capital letters for tag elements like so, notice the LI vs li

```
ayakashi
    .select("childLi")
    .where({
        tagName: {
            eq: "LI"
        }
    })
```

**Comment by zisismaras** [comment]
Hey, sorry for the late reply
Glad you figured it out! 
I should probably make it possible to use both versions
