### ISSUE TITLE
Querying  a Class with multiple names

### ISSUE THREAD

**Issue by migoya2020** [ayakashi-io/ayakashi#33]
How do i query a class div with multiple names ?
Like this  below;
`<div class="text location">Gigiri Lane Opp. Somalia, WFP, Gigiri, Nairobi, <a href="/location/nairobi" title="Companies in Nairobi" class="city445">Nairobi</a>, Kenya&nbsp;&nbsp;<a href="/company/112989/the-glass-shop#map"><i class="fa fa-map-marker" aria-hidden="true"></i> <u>View map</u></a></div>`
This is what i have tried in my Props;

`ayakashi.selectOne("address").where({ class: { eq: ".text.location" } });`

but i still cant get it right.
I have also tried 
`ayakashi.selectOne("address").where({ class: { eq: "div.text.location" } });`

Suppose i want to extract  only the text,Gigiri Lane Opp. Somalia, WFP, Gigiri, Nairobi, how should my props look like?
And if i want to get the entire text displayed under the div?
Thank you.

**Comment by zisismaras** [comment]
Hello,

In order to match multiple properties in a single query you have to use the [and](https://ayakashi.io/docs/guide/querying-with-domql.html#and) operator.

For your example you could use the following:

```javascript
    ayakashi
        .selectOne("address")
        .where({
            and: [{
                class: {
                    eq: "text"
                }
            }, {
                class: {
                    eq: "location"
                }
            }]
        });
```

Then to get the text:

```javascript
const text = await ayakashi.extractFirst("address");
```
This will get the entire text inside the div.

Hope this helps!

**Comment by migoya2020** [comment]
Thank you for your help,It  works perfectly.
now i know how to configure a complex scraping
