### ISSUE TITLE
Issue with passing arguments, especially no-sandbox

### ISSUE THREAD

**Issue by arisp8** [ayakashi-io/ayakashi#36]
The issues that I'm about to describe are a result of trying to dockerize ayakashi.

In order to run ayakashi in docker, we have to run chromedriver with the --no-sandbox option.

But, there's no way to pass the --no-sandbox option at the moment. So it would be useful to have a chrome-args option where we can pass arguments to chrome.

Secondly, --no-sandbox causes other internal issues because ayakashi uses some commands / attributes which aren't avaialble in `no-sandbox` mode.

**Comment by zisismaras** [comment]
hey @arisp8 
Passing `--no-sandbox` is generally not recommended.

Check these instructions for a workaround:
https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker

About your second point, what other issues did you face?

**Comment by arisp8** [comment]
"Passing --no-sandbox is generally not recommended"
Okay we removed this.

As for the instructions this helped us dockerize chrome so everything is running smoothly.

Thanks!
