### ISSUE TITLE
Using RegEx to exclude part of the Results

### ISSUE THREAD

**Issue by migoya2020** [ayakashi-io/ayakashi#37]
How do i exclude  some text from the results. example
```
"address": "Nairobi,Kenya Gatundu rd kileleshwa, Nairobi, NairobiView Map",
```
How do i omit "View Map"  ?

**Comment by andrewgoldenbracketgg** [comment]
let reg = new RegExp(/View Map/g)
let word = "Nairobi,Kenya Gatundu rd kileleshwa, Nairobi, NairobiView Map"
word.replace(reg, "")

Something like this will do the trick

**Comment by migoya2020** [comment]
thanks, @andrewgoldenbracketgg  but i already fixed my issues.
