### ISSUE TITLE
Feature request: extendable modules for output

### ISSUE THREAD

**Issue by magick93** [ayakashi-io/ayakashi#48]
Hello

Firstly, I have tried many different scrapers, and this is probably the best. It works. Has great documentation, is beautifully designed. Very impressed! Well done! And thank you for sharing.

# Feature Request

Along with `saveToJson` and `saveToSql` it would be good if it were possibly to create custom modules.

## User Case 01 - post to API

> As a web scraper I ultimately want to get the data into my own data store. An obvious choice to to post to my api.

## User Case 02 - call webhook / url

> As an "enterprise" user I have custom jobs that need to get triggered, that will pick up the freshly downloaded data and put it on a queue for processing...

**Comment by zisismaras** [comment]
Hi, thanks a lot for your kind words!

What you describe is already possible but it seems it's not properly documented.

Here is a little walkthrough to get you started:

Create a script that will POST results to an API:

`ayakashi new --script --name=postToAPI`

Register it on your `ayakashi.config.js` after your scrapers (like you would do with the builtin `saveToJSON` etc):

```js
module.exports = {
    waterfall: [{
        type: "scraper",
        module: "myScraper"
    }, {
        type: "script",
        module: "postToAPI"
    }]
};
```

And here is an example `postToAPI.js` script file that just POSTs the data to an API:

```js
//using the axios library for this example
const axios = require("axios");

module.exports = async function(input) {
    //input contains the data returned by the scraper
    await axios.post("https://myapi.com", {
        data: input
    });
}
```

You can add anything you need in the script file (other datastores, queue push etc).

Hope this is helpful, let me know if you have any questions!

**Comment by magick93** [comment]
Thank you!

This is very clear.
